version: "3.8"

services:
  app:
    image: swarmpit/swarmpit
    networks:
      - internal
      - databases
      - reverse_proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - SWARMPIT_DB=http://couchdb:5984
      - SWARMPIT_INFLUXDB=http://influxdb:8086
    depends_on:
      - couchdb
      - influxdb
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.50"
          memory: 1024M
        reservations:
          cpus: "0.25"
          memory: 512M
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.role==manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.swarmpit.rule=Host(`swarmpit.${DOMAIN_NAME}`)
        - traefik.http.routers.swarmpit.tls.certresolver=leresolver
        - traefik.http.routers.swarmpit.entrypoints=websecure
        - traefik.http.services.swarmpit.loadbalancer.server.port=8080

  agent:
    image: swarmpit/agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - internal
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: 64M
        reservations:
          cpus: "0.05"
          memory: 32M
      mode: global
      labels:
        - swarmpit.agent=true

networks:
  internal:
    internal: true
  reverse_proxy:
    external: true
  databases:
    external: true
