version: "3.8"

services:
  app:
    image: nextcloud
    networks:
      - ldap
      - reverse_proxy
      - databases
    volumes:
      - ${STORAGE_LOCATION}/nextcloud/app:/var/www/html
      - ${STORAGE_LOCATION}/nextcloud/data:/var/www/html/data
    secrets:
      - postgresql_postgres_password
    environment:
      - POSTGRES_HOST=postgresql
      - POSTGRES_USER=postgres
      - POSTGRES_DB=nextcloud
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_postgres_password
    deploy:
      resources:
        limits:
          cpus: "2.00"
          memory: 1024M
        reservations:
          cpus: "0.25"
          memory: 512M
      placement:
        constraints:
          - node.labels.big==true
      labels:
        - traefik.enable=true
        - traefik.http.routers.nextcloud.rule=Host(`nextcloud.${DOMAIN_NAME}`)
        - traefik.http.routers.nextcloud.tls.certresolver=leresolver
        - traefik.http.routers.nextcloud.entrypoints=websecure
        - traefik.http.services.nextcloud.loadbalancer.server.port=80
        - traefik.http.middlewares.nextcloud-redirectregex.redirectRegex.permanent=true
        - traefik.http.middlewares.nextcloud-redirectregex.redirectRegex.regex=https://(.*)/.well-known/(card|cal)dav
        - traefik.http.middlewares.nextcloud-redirectregex.redirectRegex.replacement=https://$$1/remote.php/dav/

secrets:
  postgresql_postgres_password:
    external: true

networks:
  databases:
    external: true
  ldap:
    external: true
  reverse_proxy:
    external: true
