---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: home-postgresql
provisioner: rancher.io/local-path
parameters:
  nodePath: /storage/persistent-storage
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain

---
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: home-postgresql
  namespace: default
spec:
  teamId: home
  postgresql:
    version: "15"
  numberOfInstances: 3
  volume:
    size: 5Gi
    storageClass: home-postgresql
  users:
    postgres:
      - superuser
      - createdb
  databases:
    gotify: postgres
    miniflux: postgres
    n8n: postgres
    nextcloud: postgres
    pgadmin4: postgres
    prowlarr-log: postgres
    prowlarr-main: postgres
    radarr-log: postgres
    radarr-main: postgres
    readarr-cache: postgres
    readarr-log: postgres
    readarr-main: postgres
    speedtest_tracker: postgres
