version: "3.8"

services:
  # if `ERROR: relation "ttrss_version" does not exist`, then
  # execute https://git.tt-rss.org/fox/tt-rss/raw/master/schema/ttrss_schema_pgsql.sql manually
  app:
    image: wangqiru/ttrss
    stdin_open: true
    tty: true
    networks:
      - reverse_proxy
      - databases
    secrets:
      - postgresql_postgres_password
    environment:
      - SELF_URL_PATH=https://ttrss.${DOMAIN_NAME}/
      - DB_HOST=postgresql
      - DB_PASS_FILE=/run/secrets/postgresql_postgres_password
      - ENABLE_PLUGINS=api_feedreader,auth_internal,fever
      - FEED_LOG_QUIET=true
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 1024M
        reservations:
          cpus: "0.25"
          memory: 512M
      labels:
        - traefik.enable=true
        - traefik.http.routers.ttrss.rule=Host(`ttrss.${DOMAIN_NAME}`)
        - traefik.http.routers.ttrss.tls.certresolver=leresolver
        - traefik.http.routers.ttrss.entrypoints=websecure
        - traefik.http.services.ttrss.loadbalancer.server.port=80

secrets:
  postgresql_postgres_password:
    external: true

networks:
  reverse_proxy:
    external: true
  databases:
    external: true
