{{- if .Values.primaryTenant }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: platform
  annotations:
    linkerd.io/inject: enabled
{{- end }}

---
apiVersion: v1
kind: Namespace
metadata:
  name: "{{ .Values.applicationsNamespace }}"
