# code: language=ansible
---
- name: Applying ufw rules
  when: not detect_is_openwrt
  community.general.ufw:
    to_port: "{{ item.to_port | default(omit) }}"
    proto: "{{ item.proto | default(omit) }}"
    rule: "{{ item.rule | default(omit) }}"
    comment: "{{ item.comment | default(omit) }}"
  with_items: "{{ firewall_rules }}"
  become: true
  retries: 3
  delay: 10
  register: firewall_result
  until: firewall_result is not failed
