---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: libvirt
lint: |
  set -e
  yamllint . -s -f colored
  ansible-lint --exclude ${HOME}/.ansible/roles/
platforms:
  - name: replica1
    box: cloud-image/ubuntu-24.04
    memory: 4096
    cpus: 2
    groups:
      - k3s_cluster
    interfaces:
      - type: private_network
        libvirt__network_name: molecule_network
        network_name: private_network
        ip: "192.168.123.11"
        auto_config: true
  - name: replica2
    box: cloud-image/ubuntu-24.04
    memory: 4096
    cpus: 2
    groups:
      - k3s_cluster
    interfaces:
      - type: private_network
        libvirt__network_name: molecule_network
        network_name: private_network
        ip: "192.168.123.12"
        auto_config: true
  - name: replica3
    box: cloud-image/ubuntu-24.04
    memory: 4096
    cpus: 2
    groups:
      - k3s_cluster
    interfaces:
      - type: private_network
        libvirt__network_name: molecule_network
        network_name: private_network
        ip: "192.168.123.13"
        auto_config: true
  - name: replica4
    box: cloud-image/ubuntu-24.04
    memory: 4096
    cpus: 2
    groups:
      - k3s_cluster
    interfaces:
      - type: private_network
        libvirt__network_name: molecule_network
        network_name: private_network
        ip: "192.168.123.14"
        auto_config: true
  - name: headscale1
    box: cloud-image/ubuntu-24.04
    memory: 1024
    cpus: 1
    groups:
      - headscale
    interfaces:
      - type: private_network
        libvirt__network_name: molecule_network
        network_name: private_network
        ip: "192.168.123.21"
        auto_config: true
  - name: router1
    box: arch-anes/openwrt
    box_version: "24.10"
    memory: 1024
    cpus: 1
    instance_raw_config_args:
      - "vm.synced_folder '.', '/vagrant', disabled: true"
      - "vm.synced_folder '.', '/root', disabled: true"
    groups:
      - routers
    interfaces:
      - type: private_network
        libvirt__network_name: molecule_network
        network_name: private_network
        ip: "192.168.123.1"
        auto_config: false
provisioner:
  name: ansible
  inventory:
    hosts:
      all:
        vars:
          skip_system_setup: false
          skip_firewall_setup: false
          skip_vpn_setup: false
          skip_k8s_setup: false
          skip_binary_update: false
          manifest_only_setup: false
          display_headlamp_token: false
          chartValuesOverrides:
            enableAllApplicationsByDefault: false
            highAvailability: false
      k3s_cluster:
        hosts:
          replica1:
            labels:
              - local=true
              - public=true
          replica2:
            k3s_control_node: true
          replica3:
            labels:
              - nas=true
      routers:
        hosts:
          router1:
            haproxy:
              servers:
                server1: "192.168.123.11"
                server2: "192.168.123.12"
                server3: "192.168.123.13"
  playbooks:
    converge: converge.yml
scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
