---
dependency:
  name: galaxy
  options:
    role-file: ../../requirements.yml
    requirements-file: ../../requirements.yml
driver:
  name: vagrant
lint: |
  set -e
  yamllint . -s -f colored
  ansible-lint --exclude ${HOME}/.ansible/roles/
platforms:
  - name: replica1
    groups:
      - k3s_cluster
    box: bento/ubuntu-24.04
    memory: 4096
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
  - name: replica2
    groups:
      - k3s_cluster
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
  - name: replica3
    groups:
      - k3s_cluster
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
  - name: replica4
    groups:
      - k3s_cluster
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
  - name: headscale1
    groups:
      - headscale
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        skip_system_setup: false
        skip_firewall_setup: false
        skip_vpn_setup: false
        skip_k8s_setup: false
        skip_binary_update: false
        manifest_only_setup: false
        display_k8s_dashboard_password: false
        chartValuesOverrides:
          disableAllApplications: true
    host_vars:
      replica1:
        labels:
          - local=true
          - public=true
      replica2:
        k3s_control_node: true
      replica3:
        labels:
          - nas=true
  playbooks:
    converge: converge.yml
    # verify: ../default/verify.yml
# verifier:
#   name: ansible
#   lint:
#     name: ansible-lint
