version: "3"

services:
  devcontainer:
    image: dev-container-kubernetes-ansible:libvirt
    container_name: self-hosted-services-devcontainer
    restart: unless-stopped
    volumes:
      - ../:/workspace
      - ./ansible:/etc/ansible
      - /var/run/libvirt:/var/run/libvirt:rw
      - /lib/modules:/lib/modules:ro
    devices:
      - /dev/kvm:/dev/kvm
      - /dev/net/tun:/dev/net/tun
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    environment: {}
    networks:
      - devcontainer-network
    tty: true
    stdin_open: true
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  devcontainer-network:
