# code: language=ansible
---

- name: Allocate huge pages
  when: ansible_facts['distribution'] == 'Ubuntu' and not prepare_detect_is_raspberry_pi
  become: true
  ansible.posix.sysctl:
    name: vm.nr_hugepages
    value: "{{ 1024 * (tenants_count | int) }}"  # 2Gi of huge pages per tenant, matches what's in charts/services/templates/postgresql.yaml
    sysctl_file: /etc/sysctl.d/99-k3s.conf
    state: present
    reload: true

- name: Increase inotify max user instances
  when: ansible_facts['distribution'] == 'Ubuntu'
  become: true
  ansible.posix.sysctl:
    name: fs.inotify.max_user_instances
    value: "8192"
    sysctl_file: /etc/sysctl.d/99-k3s.conf
    state: present
    reload: true

- name: Increase inotify max user watches
  when: ansible_facts['distribution'] == 'Ubuntu'
  become: true
  ansible.posix.sysctl:
    name: fs.inotify.max_user_watches
    value: "524288"
    sysctl_file: /etc/sysctl.d/99-k3s.conf
    state: present
    reload: true

- name: Configure OpenWrt kernel network driver offloading
  when: prepare_detect_is_openwrt
  block:
    - name: Query interface driver information
      ansible.builtin.command:
        cmd: "ethtool -i {{ prepare_detect_wan_interface | default('eth1') }}"
      register: system_setup_ethtool_driver
      changed_when: false
      failed_when: false

    - name: Disable GRO on buggy network drivers
      when: "'mtk_soc_eth' in (system_setup_ethtool_driver.stdout | default(''))"
      community.openwrt.uci:
        command: section
        config: ethtool
        section: "{{ prepare_detect_wan_interface | default('eth1') }}"
        type: device
        value:
          generic_receive_offload: 'off'
        autocommit: true
