# code: language=ansible
---

- name: Install Ubuntu packages
  become: true
  when: ansible_distribution == 'Ubuntu'
  block:
    - name: Install common packages
      ansible.builtin.apt:
        pkg:
          - curl
          - diffutils
          - htop
          - nnn
          - rasdaemon
          - rsync
          - sanoid
          - smartmontools
          - ufw
          - zfsutils-linux
        update_cache: true

- name: Install OpenWrt packages
  become: true
  when: is_openwrt
  block:
    - name: Install common packages
      community.general.opkg:
        name:
          - diffutils
          - ethtool
          - fish
          - haproxy
          - htop
          - ip6tables-nft
          - luci-app-sqm
          - nnn
          - procps-ng-pkill
          - tailscale
          - tmux
          - vim
