#!/usr/bin/env python3
"""Validate every HelmChart override against its generated chart schema.

The chart pull script generates ``values.schema.json`` with the ``helm schema``
plugin. This check renders the local HelmChart resources and supplies each
``spec.values`` document to its pulled chart. It runs ``helm lint`` first.
When lint fails, it also calls ``helm schema validate`` to distinguish an
invalid override from an upstream template problem. A chart with valid values
but a lint failure is reported as a warning so its upstream template defect is
visible without making this values check fail.
"""

from __future__ import annotations

import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

IGNORED_CHARTS = {"generic"}


class CheckError(Exception):
    """A required chart or Helm command is unavailable."""


@dataclass(frozen=True)
class HelmChartResource:
    """One rendered HelmChart and its upstream chart override values."""

    name: str
    chart: str
    version: str
    values: dict[str, Any]


def repo_root() -> Path:
    """Return the repository root relative to this script's fixed location.

    Both scripts live in the repository's ``scripts`` directory.  Resolving
    their path works in a Git checkout and a source archive, without relying
    on the current working directory or Git metadata.
    """
    return Path(__file__).resolve().parents[1]


def render_resources(root: Path) -> list[HelmChartResource]:
    """Return non-generic HelmChart resources rendered from ``charts/services``.

    Rendering first resolves the repository's Helm templates, so the returned
    values are the exact ``spec.values`` documents supplied to each upstream
    chart by the services chart.

    Raises:
        CheckError: If ``helm template`` cannot render the services chart.
    """
    result = subprocess.run(
        ["helm", "template", "charts/services"],
        cwd=root,
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode:
        raise CheckError(f"helm template failed:\n{result.stderr.strip()}")

    resources: list[HelmChartResource] = []
    for document in yaml.safe_load_all(result.stdout):
        if not isinstance(document, dict) or document.get("kind") != "HelmChart":
            continue
        spec = document.get("spec")
        if not isinstance(spec, dict):
            continue
        chart = str(spec.get("chart", "")).rstrip("/").rsplit("/", 1)[-1]
        if not chart or chart in IGNORED_CHARTS:
            continue
        values = spec.get("values")
        resources.append(
            HelmChartResource(
                name=str((document.get("metadata") or {}).get("name", "?")),
                chart=chart,
                version=str(spec.get("version", "")),
                values=values if isinstance(values, dict) else {},
            )
        )
    return resources


def chart_path(root: Path, resource: HelmChartResource) -> Path:
    """Return the cached chart directory after checking its required inputs.

    The cache must contain the version requested by ``resource`` and a schema
    generated by ``pull-upstream-helm-charts.py``.  Checking both here avoids
    validating overrides against stale chart defaults or schemas.

    Raises:
        CheckError: If the chart, requested version, or generated schema is
            missing.
    """
    path = root / "charts" / "services" / "upstream-charts" / resource.chart
    chart_file = path / "Chart.yaml"
    if not chart_file.is_file():
        raise CheckError(
            f"{resource.name}: chart {resource.chart} is missing; " "run scripts/pull-upstream-helm-charts.py"
        )
    chart = yaml.safe_load(chart_file.read_text()) or {}
    if str(chart.get("version", "")) != resource.version:
        raise CheckError(
            f"{resource.name}: chart {resource.chart} is version {chart.get('version')}, "
            f"but the HelmChart requests {resource.version}; "
            "run scripts/pull-upstream-helm-charts.py"
        )
    if not (path / "values.schema.json").is_file():
        raise CheckError(
            f"{resource.name}: generated schema is missing for {resource.chart}; "
            "run scripts/pull-upstream-helm-charts.py"
        )
    return path


def run_helm(command: list[str], path: Path, resource: HelmChartResource) -> subprocess.CompletedProcess[str]:
    """Run ``helm`` for a chart with a resource's values serialized to stdin.

    Callers include ``--values -`` when Helm itself must read the override
    document.  ``helm schema validate`` reads the same YAML from stdin by its
    plugin contract.  Command output is always captured so callers can choose
    whether it belongs in a pass, warning, or failure report.
    """
    return subprocess.run(
        ["helm", *command, str(path)],
        input=yaml.safe_dump(resource.values, sort_keys=False),
        capture_output=True,
        text=True,
        check=False,
    )


def main() -> int:
    """Lint each rendered override and return a process exit status.

    Helm lint is the primary check.  A failed lint is then checked with the
    generated schema: if schema validation succeeds, the values are valid and
    the lint result is retained as a warning for an upstream template issue.
    If validation also fails, the override is reported as a failure.
    """
    try:
        root = repo_root()
        resources = render_resources(root)
    except (CheckError, OSError, subprocess.CalledProcessError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    failures = 0
    warnings = 0
    for resource in resources:
        try:
            path = chart_path(root, resource)
        except CheckError as exc:
            print(f"error: {exc}", file=sys.stderr)
            failures += 1
            continue

        lint = run_helm(["lint", "--values", "-"], path, resource)
        if not lint.returncode:
            print(f"PASS {resource.name} ({resource.chart} {resource.version})", flush=True)
            continue

        validation = run_helm(["schema", "validate"], path, resource)
        if not validation.returncode:
            warnings += 1
            output = (lint.stdout + lint.stderr).strip()
            print(
                f"WARN {resource.name} ({resource.chart} {resource.version}): "
                "helm lint failed, but the override matches the generated schemas",
                file=sys.stderr,
                flush=True,
            )
            print(output, file=sys.stderr, flush=True)
            continue

        if validation.returncode:
            failures += 1
            output = (validation.stdout + validation.stderr).strip()
            print(f"FAIL {resource.name} ({resource.chart} {resource.version})", file=sys.stderr, flush=True)
            print(output, file=sys.stderr, flush=True)

    total = len(resources)
    if failures:
        print(f"{failures} of {total} HelmChart resources failed", file=sys.stderr)
        return 1
    if warnings:
        print(f"{total} HelmChart resources passed with {warnings} Helm lint warning(s)")
    else:
        print(f"{total} HelmChart resources passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
