---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-cluster
  namespace: default
type: Opaque
# stringData:
#   password: "postgrespassowrd"
#   repmgr-password: "repmgrpassowrd"
#   admin-password: "pgpoolpassowrd"

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: postgresql-cluster
  namespace: default
spec:
  chart: postgresql-ha
  repo: https://charts.bitnami.com/bitnami
  version: 12.3.2
  targetNamespace: default
  # valuesContent:
  valuesContent: |-
    # global:
    #   postgresql:
    #     existingSecret: "postgresql-cluster"
    fullnameOverride: cluster
    postgresql:
      image:
        tag: "16"
      replicaCount: 2
      affinity:
        nodeAffinity:
          # Only on storage nodes
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: storage
                    operator: In
                    values:
                      - "true"
      resources:
        requests:
          memory: 128Mi
          cpu: 250m
        limits:
          memory: 1Gi
          cpu: 2000m
      existingSecret: postgresql-cluster
      extraEnvVars:
        - name: POSTGRES_MULTIPLE_DATABASES
          value: "gotify,miniflux,n8n,nextcloud,pgadmin4,prowlarr-log,prowlarr-main,radarr-log,radarr-main,readarr-cache,readarr-log,readarr-main,speedtest_tracker"
      initdbScriptsCM:
        create-multiple-postgresql-databases.sh: |
          #!/bin/bash

          set -e
          set -u

          function create_user_and_database() {
            local database=$1
            echo "  Creating user and database '$database'"
            psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
                CREATE USER $database;
                CREATE DATABASE $database;
                GRANT ALL PRIVILEGES ON DATABASE $database TO $database;
          EOSQL
          }

          if [ -n "$POSTGRES_MULTIPLE_DATABASES" ]; then
            echo "Multiple database creation requested: $POSTGRES_MULTIPLE_DATABASES"
            for db in $(echo $POSTGRES_MULTIPLE_DATABASES | tr ',' ' '); do
              create_user_and_database $db
            done
            echo "Multiple databases created"
          fi
    witness:
      create: true
      replicaCount: 1
      affinity:
        nodeAffinity:
          # Only on storage nodes
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: witness
                    operator: In
                    values:
                      - "true"
      resources:
        requests:
          memory: 128Mi
          cpu: 250m
        limits:
          memory: 512Mi
          cpu: 1000m
    pgpool:
      resources:
        requests:
          memory: 128Mi
          cpu: 250m
        limits:
          memory: 1Gi
          cpu: 2000m
      existingSecret: postgresql-cluster
    persistence:
      storageClass: persistent
