---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-cluster
  namespace: default
type: Opaque
# stringData:
#   postgres-password: "postgrespassowrd"
#   replication-password: "replicationpassword"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-cluster-scripts
  namespace: default
data:
  create-multiple-postgresql-databases.sh: |
    #!/bin/bash

    set -e
    set -u

    export PGPASSWORD="$POSTGRES_PASSWORD"

    function create_database() {
      local database=$1
      echo "Creating database '$database'"
      psql -v ON_ERROR_STOP=1 --username postgres <<-EOSQL
          CREATE DATABASE "$database";
    EOSQL
    }

    if [ -n "$POSTGRES_MULTIPLE_DATABASES" ]; then
      echo "Multiple database creation requested: $POSTGRES_MULTIPLE_DATABASES"
      for db in $(echo $POSTGRES_MULTIPLE_DATABASES | tr ',' ' '); do
        create_database $db
      done
      echo "Multiple databases created"
    fi

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: postgresql-cluster
  namespace: default
spec:
  chart: postgresql
  repo: https://charts.bitnami.com/bitnami
  version: 13.2.24
  targetNamespace: default
  # valuesContent:
  valuesContent: |-
    image:
      tag: "16"
    architecture: replication
    global:
      storageClass: persistent
      postgresql:
        auth:
          existingSecret: postgresql-cluster
    primary:
      podLabels:
        postgresqlType: primary
      affinity:
        nodeAffinity:
          # Only on storage nodes
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: storage
                    operator: In
                    values:
                      - "true"
        podAntiAffinity:
          # Only when replica pod is not present
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: postgresqlType
                    operator: In
                    values:
                      - replica
      resources:
        requests:
          memory: 128Mi
          cpu: 250m
        limits:
          memory: 1Gi
          cpu: 2000m
      # existingSecret: postgresql-cluster
      extraEnvVars:
        - name: POSTGRES_MULTIPLE_DATABASES
          value: "gotify,miniflux,n8n,nextcloud,pgadmin4,prowlarr-log,prowlarr-main,radarr-log,radarr-main,readarr-cache,readarr-log,readarr-main,speedtest_tracker"
      initdb:
        scriptsConfigMap: postgresql-cluster-scripts
    readReplicas:
      podLabels:
        postgresqlType: replica
      affinity:
        nodeAffinity:
          # Only on storage nodes
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: storage
                    operator: In
                    values:
                      - "true"
        podAntiAffinity:
          # Only when primary pod is not present
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: postgresqlType
                    operator: In
                    values:
                      - primary
      resources:
        requests:
          memory: 128Mi
          cpu: 250m
        limits:
          memory: 1Gi
          cpu: 2000m
