---
when:
  - event: pull_request
  - event: push
    branch:
      - main
      - dev

steps:
  - name: Restore Helm chart cache
    image: pgsty/mc
    environment: &minio_environment
      MINIO_ACCESS_KEY:
        from_secret: minio_access_key
      MINIO_SECRET_KEY:
        from_secret: minio_secret_key
    commands:
      - &minio_setup mc alias set minio http://minio "$MINIO_ACCESS_KEY" "$MINIO_SECRET_KEY"
      - mc mirror --overwrite --preserve --summary "minio/woodpecker-cache/upstream-charts/$CI_COMMIT_BRANCH/" charts/services/upstream-charts/
    failure: ignore

  - name: Lint Ansible and Kubernetes
    image: ghcr.io/arch-anes/dev-container-kubernetes-ansible:latest
    depends_on:
      - Restore Helm chart cache
    commands:
      - ansible-lint
      - helm format --check charts/services
      - helm lint charts/services
      - helm unittest charts/services
      - helm template charts/services | yamllint --no-warnings -
      - yamllint .
      - yamlfmt -lint
      - python3 scripts/check-helm-chart-values.py

  - name: Save Helm chart cache
    image: pgsty/mc
    depends_on:
      - Lint Ansible and Kubernetes
    environment: *minio_environment
    commands:
      - *minio_setup
      - mc mirror --overwrite --preserve --summary charts/services/upstream-charts/ "minio/woodpecker-cache/upstream-charts/$CI_COMMIT_BRANCH/"
    failure: ignore
    when:
      status:
        - success

  - name: Lint Python
    image: mcr.microsoft.com/devcontainers/python:3
    commands:
      - black --check .
