---
when:
  - event: pull_request
  - event: push
    branch:
      - main
      - dev

steps:
  - name: Restore Helm chart cache
    image: ghcr.io/arch-anes/dev-container-kubernetes-ansible:latest
    volumes:
      - woodpecker-cache:/cache
    commands:
      - mkdir -p .cache/upstream-charts "/cache/upstream-charts/$CI_COMMIT_BRANCH"
      - rsync -a --delete --stats --human-readable "/cache/upstream-charts/$CI_COMMIT_BRANCH/" .cache/upstream-charts/
    failure: ignore

  - name: Lint Ansible and Kubernetes
    image: ghcr.io/arch-anes/dev-container-kubernetes-ansible:latest
    depends_on:
      - Restore Helm chart cache
    commands:
      - ansible-lint
      - helm format --check charts/services
      - helm lint charts/services
      - helm unittest charts/services
      - helm template charts/services | yamllint --no-warnings -
      - yamllint .
      - yamlfmt -lint
      - python3 scripts/check-helm-chart-values.py

  - name: Save Helm chart cache
    image: ghcr.io/arch-anes/dev-container-kubernetes-ansible:latest
    depends_on:
      - Lint Ansible and Kubernetes
    volumes:
      - woodpecker-cache:/cache
    commands:
      - mkdir -p "/cache/upstream-charts/$CI_COMMIT_BRANCH"
      - rsync -a --delete --stats --human-readable .cache/upstream-charts/ "/cache/upstream-charts/$CI_COMMIT_BRANCH/"
    failure: ignore
    when:
      status:
        - success

  - name: Lint Python
    image: mcr.microsoft.com/devcontainers/python:3
    commands:
      - black --check .
