---
steps:
  - name: Lint Ansible and Kubernetes
    image: ghcr.io/arch-anes/dev-container-kubernetes-ansible:latest
    commands:
      - ansible-lint
      - helm lint charts/services
      - helm unittest charts/services
      - helm template charts/services | kubeconform -summary -schema-location default -schema-location 'https://raw.githubusercontent.com/abelfodil/CRDs-catalog/helmchart/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json'
      - helm template charts/services | yamllint --no-warnings -
      - yamllint .
      - yamlfmt -lint
      - python3 scripts/pull-upstream-helm-charts.py
      - python3 scripts/check-helm-chart-values.py

  - name: Lint Python
    image: mcr.microsoft.com/devcontainers/python:3
    commands:
      - black --check .
