---
when:
  - event: pull_request
    path: &path
      - "charts/**"
      - "group_vars/**"
      - "molecule/**"
      - "roles/**"
      - requirements.yml
      - setup_cluster.yml
      - setup_router.yml
      - teardown_cluster.yml
  - event: push
    branch:
      - main
      - dev
    path: *path

depends_on:
  - lint

steps:
  - name: Restore Vagrant box cache
    image: ghcr.io/arch-anes/dev-container-kubernetes-ansible:latest
    volumes:
      - woodpecker-cache:/cache
    commands:
      - mkdir -p .cache/vagrant/boxes /cache/vagrant/boxes
      - rsync -a --delete --stats --human-readable /cache/vagrant/boxes/ .cache/vagrant/boxes/
    failure: ignore

  - name: molecule-test
    image: ghcr.io/arch-anes/dev-container-kubernetes-ansible:latest
    privileged: true
    depends_on:
      - Restore Vagrant box cache
    commands:
      - mkdir -p "$HOME/.vagrant.d" .cache/vagrant/boxes
      - rmdir "$HOME/.vagrant.d/boxes"
      - ln -sT "$PWD/.cache/vagrant/boxes" "$HOME/.vagrant.d/boxes"
      - sudo chmod 666 /dev/kvm /dev/vhost-net /dev/net/tun
      - sudo virtlogd -d
      - sudo libvirtd -d
      - sudo chmod 666 /var/run/libvirt/libvirt-sock
      - ansible-galaxy install -r requirements.yml
      - molecule test

  - name: Save Vagrant box cache
    image: ghcr.io/arch-anes/dev-container-kubernetes-ansible:latest
    depends_on:
      - molecule-test
    volumes:
      - woodpecker-cache:/cache
    commands:
      - mkdir -p /cache/vagrant/boxes
      - rsync -a --delete --stats --human-readable .cache/vagrant/boxes/ /cache/vagrant/boxes/
    failure: ignore
    when:
      status:
        - failure
        - success
