{{- if (include "app.enabled" (list . "filebrowser")) }}
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: filebrowser
  namespace: "{{ .Values.applicationsNamespace }}"
spec:
  chart: oci://oci.trueforge.org/truecharts/filebrowser
  version: 13.6.0
  targetNamespace: "{{ .Values.applicationsNamespace }}"
  serverSide: "true"
  forceConflicts: true
  values:
    workload:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        podSpec:
          nodeSelector:
            nas: "true"
          annotations:
            backup.velero.io/backup-volumes: config
          containers:
            main:
              env:
                FB_DATABASE: /config/filebrowser.db
                FB_CONFIG: /config/filebrowser.json
    resources:
      requests:
        memory: {{ include "app.resources.memory" (list $ "128Mi") }}
        cpu: {{ include "app.resources.cpu" (list $ "250m") }}
      limits:
        memory: 2Gi
        cpu: null
    global:
      traefik:
        fixedMiddlewares: []
    ingress:
      main:
        enabled: true
        annotations:
          homer.service.name: Media
          homer.item.name: filebrowser
          homer.item.logo: "https://raw.githubusercontent.com/filebrowser/filebrowser/129a4fd39d550bd2a449575cf93f061593e39102/frontend/public/img/logo.svg"
        hosts:
          - host: filebrowser.{{ .Values.fqdn }}
            paths:
              - path: /
        tls:
          - secretName: "{{ .Values.fqdn }}-tls"
            hosts:
              - filebrowser.{{ .Values.fqdn }}
    persistence:
      config:
        type: pvc
        storageClass: local-path-persistent-namespaced
      data:
        enabled: true
        type: pvc
        existingClaim: multimedia
        subPath: Miscellaneous
        mountPath: /data
      database:
        enabled: false
{{- end }}
