{{- if (include "app.enabled" (list . "flaresolverr")) }}
{{- include "app.require" (list . "Flaresolverr" "gluetun" "Gluetun") -}}
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: flaresolverr
  namespace: "{{ .Values.applicationsNamespace }}"
spec:
  chart: oci://oci.trueforge.org/truecharts/flaresolverr
  version: 17.7.0
  targetNamespace: "{{ .Values.applicationsNamespace }}"
  serverSide: "true"
  forceConflicts: true
  values:
    {{- include "tunnel.truecharts.image" . | nindent 4 }}
    workload:
      main:
        podSpec:
          containers:
            {{- include "tunnel.truecharts.container" . | nindent 12 }}
            main:
              probes:
                readiness:
                  enabled: true
                  type: http
                  path: /
                liveness:
                  enabled: true
                  type: http
                  path: /
                startup:
                  enabled: true
                  type: http
                  path: /
              env: {}
    resources:
      requests:
        memory: {{ include "app.resources.memory" (list $ "512Mi") }}
        cpu: {{ include "app.resources.cpu" (list $ "250m") }}
      limits:
        memory: 2Gi
        cpu: null
    persistence:
      config:
        enabled: false
{{- end }}
