{{- if (include "app.enabled" (list . "frigate")) }}
{{- $gpuVendor := dig "gpu_vendor" "" (.Values.applications.frigate | default dict) -}}
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: frigate
  namespace: "{{ .Values.applicationsNamespace }}"
spec:
  chart: oci://oci.trueforge.org/truecharts/frigate
  version: 19.6.0
  targetNamespace: "{{ .Values.applicationsNamespace }}"
  # default-values: https://github.com/trueforge-org/truecharts/blob/master/charts/stable/frigate/values.yaml
  values:
    {{- $gpuVendor := .Values.applications.frigate.gpu_vendor }}
    workload:
      main:
        podSpec:
          nodeSelector:
            # Schedule only on NAS nodes
            nas: "true"
          annotations:
            backup.velero.io/backup-volumes: config
          initContainers:
            init-config:
              enabled: true
              command:
                - /bin/sh
                - -c
                - |
                  mkdir -p /config
                  if [ ! -f /config/config.yml ]; then
                    echo "Config file not found, copying initial config..."
                    cp /initial-config/config.yml /config/config.yml
                    echo "Config file copied, you can now edit it at /config/config.yml"
                  else
                    echo "Config file found, you can edit it at /config/config.yml"
                  fi
          containers:
            main:
              {{- if eq $gpuVendor "nvidia" }}
              imageSelector: tensorrtImage
              {{- end }}
              probes:
                liveness:
                  type: http
                  path: /api/
                  port: 5000
                readiness:
                  type: http
                  path: /api/
                  port: 5000
                startup:
                  type: http
                  path: /api/
                  port: 5000
              env:
                {{- if (eq $gpuVendor "nvidia") }}
                YOLO_MODELS: yolov7-320
                {{- end }}
              resources:
                requests:
                  memory: 1Gi
                  cpu: 250m
                limits:
                  cpu: null
                  memory: 4Gi
                  {{- include "gpu.device" (list . "Frigate" $gpuVendor) | nindent 18 }}
    global:
      traefik:
        fixedMiddlewares: []
    service:
      main:
        ports:
          main:
            targetPort: 8971
    ingress:
      main:
        enabled: true
        annotations:
          homer.service.name: Monitoring
          homer.item.logo: "https://raw.githubusercontent.com/blakeblackshear/frigate/37ea6b46b51e459a51f25f29fead2797e0fa04a4/docs/static/img/branding/logo.svg"
        hosts:
          - host: frigate.{{ .Values.fqdn }}
            paths:
              - path: /
        tls:
          - secretName: "{{ .Values.fqdn }}-tls"
            hosts:
              - frigate.{{ .Values.fqdn }}
    configmap:
      initial-config:
        enabled: true
        data:
          config.yml: |-
            tls:
              enabled: false
            mqtt:
              enabled: false
            cameras: {}
            {{- if or (eq $gpuVendor "intel") (eq $gpuVendor "intel_xe") }}
            detectors:
              ov:
                type: openvino
                device: GPU
            model:
              width: 300
              height: 300
              input_tensor: nhwc
              input_pixel_format: bgr
              path: /openvino-model/ssdlite_mobilenet_v2.xml
              labelmap_path: /openvino-model/coco_91cl_bkgr.txt
            {{- else if eq $gpuVendor "nvidia" }}
            detectors:
              tensorrt:
                type: tensorrt
                device: 0
            model:
              path: /config/model_cache/tensorrt/yolov7-320.trt
              labelmap_path: /labelmap/coco-80.txt
              input_tensor: nchw
              input_pixel_format: rgb
              width: 320
              height: 320
            {{- else }}
            detectors:
              cpu1:
                type: cpu
            {{- end }}
            {{- if eq $gpuVendor "nvidia" }}
            ffmpeg:
              hwaccel_args: preset-nvidia
            {{- else if $gpuVendor }}
            ffmpeg:
              hwaccel_args: preset-vaapi
            {{- end }}
    persistence:
      initial-config:
        enabled: true
        type: configmap
        objectName: initial-config
        targetSelector:
          main:
            init-config:
              subPath: config.yml
              mountPath: /initial-config/config.yml
              readOnly: true
      config:
        enabled: true
        storageClass: local-path-persistent-namespaced
        size: 1Gi
      media:
        enabled: true
        existingClaim: multimedia
        subPath: CCTV
{{- end }}
