{{- if (include "app.enabled" (list . "gotify")) }}
{{- include "app.require" (list . "Gotify" "postgresql" "PostgreSQL") -}}
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: gotify
  namespace: "{{ .Values.applicationsNamespace }}"
spec:
  chart: gotify
  repo: https://arch-anes.github.io/charts
  version: 1.0.0
  targetNamespace: "{{ .Values.applicationsNamespace }}"
  # default-values: https://github.com/arch-anes/charts/blob/main/charts/gotify/values.yaml
  values:
    workload:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        podSpec:
          containers:
            main:
              env:
                GOTIFY_DATABASE_DIALECT: postgres
                DATABASE_PASSWORD:
                  secretKeyRef:
                    name: postgresql-pguser-gotify
                    key: password
                    expandObjectName: false
                GOTIFY_DATABASE_CONNECTION: host=postgresql-primary port=5432 user=gotify dbname=gotify password=$(DATABASE_PASSWORD)
                PGSSLMODE: verify-full
                PGSSLROOTCERT: /etc/postgres/tls/ca.crt
                PGSSLCERT: /etc/postgres/tls/tls.crt
                PGSSLKEY: /etc/postgres/tls/tls.key
    resources:
      requests:
        memory: 128Mi
        cpu: 250m
      limits:
        memory: 256Mi
        cpu: null
    global:
      traefik:
        fixedMiddlewares: []
    ingress:
      main:
        enabled: true
        annotations:
          homer.service.name: Feed
          homer.item.logo: "https://raw.githubusercontent.com/gotify/logo/87aef9091f51644eaccf78e7b67f8ce94271efeb/gotify-logo.png"
        hosts:
          - host: gotify.{{ .Values.fqdn }}
            paths:
              - path: /
        tls:
          - secretName: "{{ .Values.fqdn }}-tls"
            hosts:
              - gotify.{{ .Values.fqdn }}
    persistence:
      data:
        type: emptyDir
      postgres-tls:
        enabled: true
        type: secret
        objectName: postgresql-cluster-cert
        expandObjectName: false
        mountPath: /etc/postgres/tls
        readOnly: true
        defaultMode: "0400"
{{- end }}
