{{- if (include "app.enabled" (list . "homer_operator")) }}
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: homer-operator
  namespace: "{{ .Values.applicationsNamespace }}"
spec:
  chart: homer-operator
  repo: https://arch-anes.github.io/homer-operator/
  version: 0.2.26
  targetNamespace: "{{ .Values.applicationsNamespace }}"
  serverSide: "true"
  forceConflicts: true
  values:
    watchedNamespaces:
      - {{ .Values.applicationsNamespace }}
{{- if .Values.primaryTenant }}
      - kube-system
{{- end }}
    replicaCount: {{ include "ha.replicas" . }}
    podAnnotations:
      reloader.stakater.com/auto: "true"
    resources:
      requests:
        memory: {{ include "app.resources.memory" (list $ "32Mi") }}
        cpu: {{ include "app.resources.cpu" (list $ "125m") }}
      limits:
        memory: 64Mi
    ingress:
      enabled: true
      annotations:
        homer.item.excluded: "true"
      hosts:
        - host: dash.{{ .Values.fqdn }}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: "{{ .Values.fqdn }}-tls"
          hosts:
            - dash.{{ .Values.fqdn }}
    baseConfig: |
      ---
      title: "Dashboard"
      subtitle: "Homer"
      logo: "logo.png"

      header: false
      footer: false
{{- end }}
