{{- if (include "app.enabled" (list . "homepage")) }}
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: homepage
  namespace: "{{ .Values.applicationsNamespace }}"
spec:
  chart: oci://oci.trueforge.org/truecharts/homepage
  version: 13.1.1
  targetNamespace: "{{ .Values.applicationsNamespace }}"
  serverSide: "true"
  forceConflicts: true
  values:
    forceConfigFromValues: true
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                HOMEPAGE_ALLOWED_HOSTS: "dash.{{ .Values.fqdn }}"
    configmap:
      config:
        enabled: true
        data:
          settings.yaml: |
            ---
            title: "Dashboard"
            subtitle: "Homer"
            logo: "logo.png"
            headerStyle: "clean"
          kubernetes.yaml: |
            ---
            mode: cluster
          services.yaml: |
            ---
            # Discovered via Ingress
          widgets.yaml: |
            ---
            # No default widgets to match Homer
          bookmarks.yaml: |
            ---
            # No bookmarks
    persistence:
      config:
        enabled: true
        type: emptyDir
    ingress:
      main:
        enabled: true
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: "Administration"
          gethomepage.dev/name: "Homepage"
          gethomepage.dev/icon: "https://truecharts.org/img/hotlink-ok/chart-icons/homepage.webp"
        hosts:
          - host: dash.{{ .Values.fqdn }}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: "{{ .Values.fqdn }}-tls"
            hosts:
              - dash.{{ .Values.fqdn }}
{{- end }}
