{{- if and .Values.primaryTenant (include "app.enabled" (list . "idrac_exporter")) }}
{{- include "app.require" (list . "iDRAC Exporter" "prometheus" "Prometheus") -}}

# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: idrac-exporter-config
#   namespace: kube-system
# type: Opaque
# stringData:
#   idrac.yml: |
#     address: 0.0.0.0
#     port: 9348
#     timeout: 60
#     hosts:
#       host1:
#         username: USERNAME
#         password: PASSWORD
#       host2:
#         username: USERNAME
#         password: PASSWORD
#     metrics:
#       all: true

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: idrac-exporter
  namespace: kube-system
spec:
  chart: idrac-exporter
  repo: https://mrlhansen.github.io/idrac_exporter
  version: 2.6.1
  targetNamespace: kube-system
  values:
    deploymentAnnotations:
      reloader.stakater.com/auto: "true"
    existingSecret: idrac-exporter-config
    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: {{ include "app.resources.cpu" (list $ "250m") }}
        memory: {{ include "app.resources.memory" (list $ "128Mi") }}
    prometheus:
      scrapeConfig:
        enabled: true
{{- end }}
