{{- if and .Values.primaryTenant (not .Values.disableAllApplications) .Values.applications.intel_gpu.enabled }}
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: intel-device-plugins-operator
  namespace: kube-system
spec:
  chart: intel-device-plugins-operator
  repo: https://intel.github.io/helm-charts/
  version: 0.35.0
  targetNamespace: kube-system
  # default-values: https://github.com/intel/helm-charts/blob/main/charts/device-plugin-operator/values.yaml

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: intel-gpu
  namespace: kube-system
spec:
  chart: intel-device-plugins-gpu
  repo: https://intel.github.io/helm-charts/
  version: 0.35.0
  targetNamespace: kube-system
  # default-values: https://github.com/intel/helm-charts/blob/main/charts/gpu-device-plugin/values.yaml
  values:
    tolerations:
      - key: "dedicated"
        operator: Equal
        value: "ai"
        effect: "NoSchedule"
    resourceManager: false
    sharedDevNum: 10
{{- end }}
