{{- if and (not .Values.disableAllApplications) .Values.applications.jellyseerr.enabled }}
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: seerr
  namespace: "{{ .Values.applicationsNamespace }}"
spec:
  chart: oci://oci.trueforge.org/truecharts/seerr
  version: 15.3.0
  targetNamespace: "{{ .Values.applicationsNamespace }}"
  # default-values: https://github.com/trueforge-org/truecharts/blob/master/charts/stable/seerr/values.yaml
  values:
    workload:
      main:
        podSpec:
          nodeSelector:
            # Schedule only on NAS nodes
            nas: "true"
          annotations:
            backup.velero.io/backup-volumes: config
    resources:
      requests:
        memory: 128Mi
        cpu: 1000m
      limits:
        memory: 1Gi
        cpu: ''
    global:
      traefik:
        fixedMiddlewares: []
    ingress:
      main:
        enabled: true
        annotations:
          homer.service.name: Arr
          homer.service.logo: "fas fa-ship"
          homer.service.rank: "3"
          homer.item.rank: "1"
          homer.item.logo: "https://raw.githubusercontent.com/Fallenbagel/jellyseerr/54cfeefe74de2c7df97491aa6cb954b94759ac5d/public/logo_stacked.svg"
        hosts:
          - host: jellyseerr.{{ .Values.fqdn }}
            paths:
              - path: /
        tls:
          - secretName: "{{ .Values.fqdn }}-tls"
            hosts:
              - jellyseerr.{{ .Values.fqdn }}
    persistence:
      config:
        type: pvc
        storageClass: local-path-persistent-namespaced
{{- end }}
