---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path-ephemeral
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
parameters:
  nodePath: /storage
  pathPattern: "{{`cluster-local-storage/{{ .PVName }}_{{ .PVC.Namespace }}_{{ .PVC.Name }}`}}"

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path-persistent
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
parameters:
  nodePath: /storage
  pathPattern: "{{`{{ .PVC.Name }}`}}"
