{{- if (include "app.enabled" (list . "minecraft_bedrock")) }}
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: minecraft-bedrock
  namespace: "{{ .Values.applicationsNamespace }}"
spec:
  chart: oci://oci.trueforge.org/truecharts/minecraft-bedrock
  version: 14.14.0
  targetNamespace: "{{ .Values.applicationsNamespace }}"
  serverSide: "true"
  forceConflicts: true
  values:
    service:
      main:
        type: NodePort
        ports:
          main:
            nodePort: 30778
    workload:
      main:
        podSpec:
          annotations:
            backup.velero.io/backup-volumes: config
          containers:
            main:
              probes:
                liveness:
                  spec:
                    periodSeconds: 10
                readiness:
                  spec:
                    periodSeconds: 10
                startup:
                  spec:
                    periodSeconds: 10
              env:
                EULA: true
                ENABLE_LAN_VISIBILITY: true
                VERSION: "LATEST"
                SERVER_NAME: null
                GAMEMODE: "survival"
                DIFFICULTY: null
                LEVEL_TYPE: null
                ALLOW_CHEATS: false
                MAX_PLAYERS: null
                ONLINE_MODE: true
                WHITE_LIST: false
                # WHITE_LIST_USERS: "USER:XUID,USER:XUID"
                VIEW_DISTANCE: null
                TICK_DISTANCE: null
                PLAYER_IDLE_TIMEOUT: null
                MAX_THREADS: null
                LEVEL_NAME: "Bedrock level"
                LEVEL_SEED: ""
                DEFAULT_PLAYER_PERMISSION_LEVEL: "member"
                TEXTUREPACK_REQUIRED: false
                SERVER_AUTHORITATIVE_MOVEMENT: server-auth
                PLAYER_MOVEMENT_SCORE_THRESHOLD: null
                PLAYER_MOVEMENT_DISTANCE_THRESHOLD: null
                PLAYER_MOVEMENT_DURATION_THRESHOLD_IN_MS: null
                CORRECT_PLAYER_MOVEMENT: false
    resources:
      requests:
        memory: {{ include "app.resources.memory" (list $ "1Gi") }}
        cpu: {{ include "app.resources.cpu" (list $ "2000m") }}
      limits:
        memory: 4Gi
        cpu: null
    persistence:
      config:
        enabled: true
        type: pvc
        storageClass: local-path-persistent-namespaced
        size: 10Gi
{{- end }}
