{{- if and .Values.primaryTenant (include "app.enabled" (list . "node_problem_detector")) }}
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: node-problem-detector
  namespace: kube-system
spec:
  chart: oci://ghcr.io/deliveryhero/helm-charts/node-problem-detector
  version: 2.4.1
  targetNamespace: kube-system
  serverSide: "true"
  forceConflicts: true
  values:
    metrics:
      enabled: {{ include "metrics.enabled" . }}
      serviceMonitor:
        enabled: {{ include "metrics.enabled" . }}
      prometheusRule:
        enabled: {{ include "metrics.enabled" . }}
    resources:
      requests:
        cpu: {{ include "app.resources.cpu" (list $ "100m") }}
        memory: {{ include "app.resources.memory" (list $ "128Mi") }}
      limits:
        memory: 512Mi
{{- end }}
