{{- if .Values.primaryTenant }}
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: node-feature-discovery
  namespace: kube-system
spec:
  chart: oci://registry.k8s.io/nfd/charts/node-feature-discovery
  version: 0.19.0
  targetNamespace: kube-system
  serverSide: "true"
  forceConflicts: true
  values:
    featureGates:
      NodeFeatureAPI: true
      NodeFeatureGroupAPI: true
    master:
      resources:
        requests:
          cpu: {{ include "app.resources.cpu" (list $ "100m") }}
          memory: {{ include "app.resources.memory" (list $ "128Mi") }}
        limits:
          memory: 128Mi
    worker:
      tolerations:
        - effect: "NoSchedule"
          operator: Exists
      resources:
        requests:
          cpu: {{ include "app.resources.cpu" (list $ "100m") }}
          memory: {{ include "app.resources.memory" (list $ "128Mi") }}
        limits:
          memory: 128Mi
    prometheus:
      enabled: {{ include "metrics.enabled" . | default false }}
{{- end }}
