{{- if and (not .Values.disableAllApplications) .Values.applications.octoprint.enabled }}
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: octoprint
  namespace: "{{ .Values.applicationsNamespace }}"
spec:
  chart: oci://oci.trueforge.org/truecharts/octoprint
  version: 17.2.0
  targetNamespace: "{{ .Values.applicationsNamespace }}"
  # default-values: https://github.com/trueforge-org/truecharts/blob/master/charts/stable/octoprint/values.yaml
  values:
    workload:
      main:
        strategy: Recreate
        podSpec:
          nodeSelector:
            kubernetes.io/arch: ""
          annotations:
            backup.velero.io/backup-volumes: data
          containers:
            main:
              env:
                ENABLE_MJPG_STREAMER: "true"
                MJPG_STREAMER_INPUT: "-fps 30 -r 1920x1080"
    service:
      webcam:
        enabled: true
        ports:
          webcam:
            enabled: true
            port: 8080
            targetPort: 8080
    resources:
      requests:
        memory: 512Mi
        cpu: 2000m
      limits:
        memory: 2Gi
        cpu: ''
        {{- range .Values.applications.octoprint.devices }}
        {{ . }}: "1"
        {{- end }}
    global:
      traefik:
        fixedMiddlewares: []
    ingress:
      main:
        enabled: true
        annotations:
          homer.service.name: Automation
          homer.item.logo: "https://raw.githubusercontent.com/OctoPrint/OctoPrint/a93b4d397248dc406a75e634c1326fb1b8ddcb63/docs/images/octoprint-logo.png"
        hosts:
          - host: octoprint.{{ .Values.fqdn }}
            paths:
              - path: /
        tls:
          - secretName: "{{ .Values.fqdn }}-tls"
            hosts:
              - octoprint.{{ .Values.fqdn }}
      webcam:
        enabled: true
        annotations:
          homer.item.excluded: "true"
          traefik.ingress.kubernetes.io/router.middlewares: kube-system-cluster-admin-authentication@kubernetescrd
        hosts:
          - host: octoprint-webcam.{{ .Values.fqdn }}
            paths:
              - path: /
        tls:
          - secretName: "{{ .Values.fqdn }}-tls"
            hosts:
              - octoprint-webcam.{{ .Values.fqdn }}
        targetSelector:
          webcam: webcam
    persistence:
      data:
        type: pvc
        storageClass: local-path-persistent-namespaced
{{- end }}
