{{- if and (not .Values.disableAllApplications) .Values.applications.odoo.enabled }}
{{- if not .Values.applications.postgresql.enabled }}
{{- fail "Odoo requires PostgreSQL to be enabled. Please enable PostgreSQL in your values.yaml" }}
{{- end }}
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: odoo
  namespace: "{{ .Values.applicationsNamespace }}"
spec:
  chart: oci://oci.trueforge.org/truecharts/odoo
  version: 22.12.4
  targetNamespace: "{{ .Values.applicationsNamespace }}"
  # reference: https://github.com/trueforge-org/truecharts/blob/master/charts/stable/odoo/values.yaml
  values:
    workload:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        podSpec:
          annotations:
            backup.velero.io/backup-volumes: odoo
          initContainers:
            init-db:
              enabled: false
          containers:
            main:
              args:
                - --init=base
                - --without-demo=all
              {{- if .Values.applications.odoo.updatePluginsOnStartup }}
                - --update=all
              {{- end }}
              probes:
                liveness:
                  spec:
                    periodSeconds: 30
                    failureThreshold: 10
                readiness:
                  spec:
                    periodSeconds: 30
                    failureThreshold: 10
              {{- if .Values.applications.odoo.updatePluginsOnStartup }}
                startup:
                  spec:
                    initialDelaySeconds: 600
              {{- end }}
              env:
                HOST: postgresql-primary
                USER: odoo
                DATABASE: odoo
                PGSSLROOTCERT: /etc/postgres/tls/ca.crt
                PGSSLCERT: /etc/postgres/tls/tls.crt
                PGSSLKEY: /etc/postgres/tls/tls.key
                PASSWORD:
                  secretKeyRef:
                    name: postgresql-pguser-odoo
                    key: password
                    expandObjectName: false
    configmap:
      odoo-config:
        enabled: false
      config:
        enabled: true
        data:
          odoo.conf: |-
            [options]
            ; Paths
            data_dir = /var/lib/odoo
            addons_path = /var/lib/odoo/extra-addons
            ; Network Details
            http_enable = True
            http_port = 8069
            proxy_mode = True
            ; Database Details
            db_name = odoo
            db_sslmode = verify-full
            ; Required to avoid the selector
            admin_passwd = admin
            list_db = False
      authentik-blueprint:
        enabled: {{ .Values.applications.authentik.enabled }}
        data:
          blueprint.yaml: |
            # yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
            version: 1
            metadata:
              name: Odoo Blueprint
            entries:
              # ---- Service Account ----
              - id: odoo-service-account
                model: authentik_core.user
                identifiers:
                  username: odoo
                attrs:
                  name: "Odoo Service Account"
                  email: "odoo@{{ .Values.fqdn }}"
                  password: !File /blueprints/mounted/secret-odoo/odoo_sa_password
                  is_active: true
                  type: service_account
                  attributes:
                    mailLocalAddress: "odoo@{{ .Values.fqdn }}"
                    mailAlias:
                      - bounce@{{ .Values.fqdn }}
                      - customer-care@{{ .Values.fqdn }}
                      - expense@{{ .Values.fqdn }}
                      - inbox@{{ .Values.fqdn }}
                      - lead@{{ .Values.fqdn }}
                      - notifications@{{ .Values.fqdn }}
                      - odoobot@{{ .Values.fqdn }}
                      - purchases@{{ .Values.fqdn }}
                      - rfq@{{ .Values.fqdn }}
                      - sales@{{ .Values.fqdn }}
                      - to-do@{{ .Values.fqdn }}
    resources:
      requests:
        memory: 500Mi
        cpu: 250m
      limits:
        memory: 1Gi
        cpu: null
    global:
      traefik:
        fixedMiddlewares: []
    ingress:
      main:
        enabled: true
        annotations:
          homer.service.name: Administration
          homer.item.logo: "https://odoocdn.com/openerp_website/static/src/img/assets/svg/odoo_logo.svg"
        hosts:
          - host: odoo.{{ .Values.fqdn }}
            paths:
              - path: /
        tls:
          - secretName: "{{ .Values.fqdn }}-tls"
            hosts:
              - odoo.{{ .Values.fqdn }}
    persistence:
      postgresql-certs:
        enabled: true
        type: secret
        objectName: postgresql-cluster-cert
        expandObjectName: false
        mountPath: /etc/postgres/tls
        readOnly: true
        defaultMode: "0400"
      odoo:
        type: pvc
        storageClass: local-path-persistent-namespaced
      addons:
        enabled: false
      odoo-config:
        objectName: config
    cnpg:
      main:
        enabled: false
        creds:
          host: "dummy"
          password: "dummy"
{{- if .Values.applications.authentik.enabled }}
    extraTpl:
      - apiVersion: external-secrets.io/v1
        kind: ExternalSecret
        metadata:
          name: odoo
          namespace: "{{ .Values.applicationsNamespace }}"
        spec:
          refreshPolicy: CreatedOnce
          creationPolicy: Owner
          deletionPolicy: Retain
          target:
            name: odoo
          dataFrom:
            - sourceRef:
                generatorRef:
                  apiVersion: generators.external-secrets.io/v1alpha1
                  kind: ClusterGenerator
                  name: huge-ascii-password-generator
              rewrite:
                - transform:
                    template: odoo_sa_password
{{- end }}
{{- end }}
