{{- if .Values.applications.prometheus.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: prometheus
  namespace: kube-system
type: Opaque
# stringData:
#   grafana-admin-user: "someuser"
#   grafana-admin-password: "somepass"

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rancher-monitoring-crd
  namespace: kube-system
spec:
  chart: rancher-monitoring-crd
  repo: https://charts.rancher.io/
  version: 106.0.0
  targetNamespace: kube-system

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rancher-monitoring
  namespace: kube-system
spec:
  chart: rancher-monitoring
  repo: https://charts.rancher.io/
  version: 106.0.0
  targetNamespace: kube-system
  valuesContent: |-
    # accounts for kube-controller-manager, kube-scheduler, and kube-proxy metrics
    namespaceOverride: kube-system
    prometheus-adapter:
      prometheus:
        url: http://rancher-monitoring-prometheus.kube-system.svc
    k3sServer:
      enabled: true
    rke2Etcd:
      enabled: true
    grafana:
      admin:
        existingSecret: "prometheus"
        userKey: grafana-admin-user
        passwordKey: grafana-admin-password
      ingress:
        enabled: true
        annotations:
          homer.service.name: Monitoring
          homer.item.logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Grafana_logo.svg/1920px-Grafana_logo.svg.png"
          traefik.ingress.kubernetes.io/router.middlewares: kube-system-intranet-allowlist@kubernetescrd
        hosts:
          - grafana.{{ .Values.fqdn }}
        tls:
          - secretName: "{{ .Values.fqdn }}-tls"
            hosts:
              - grafana.{{ .Values.fqdn }}
      persistence:
        enabled: true
        storageClassName: "local-path-retain"
        accessModes:
          - ReadWriteOnce
        size: 20Gi
        finalizers:
          - kubernetes.io/pvc-protection
      nodeSelector:
        # Schedule onto amd64 to specifically avoid raspberry pi to not wear the SD card
        kubernetes.io/arch: amd64
    prometheusSpec:
      retention: 365d
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 50Gi
      nodeSelector:
        # Schedule onto amd64 to specifically avoid raspberry pi to not wear the SD card
        kubernetes.io/arch: amd64
{{- end }}
