{{- if .Values.applications.prometheus.enabled }}
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: prometheus
#   namespace: kube-system
# type: Opaque
# stringData:
#   grafana-admin-user: "someuser"
#   grafana-admin-password: "somepass"

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: prometheus
  namespace: kube-system
spec:
  chart: rancher-monitoring
  repo: https://charts.rancher.io/
  version: 107.1.0
  targetNamespace: kube-system
  valuesContent: |-
    namespaceOverride: kube-system
    rancherMonitoring:
      enabled: false
    prometheus-adapter:
      prometheus:
        url: http://rancher-monitoring-prometheus.kube-system.svc
    k3sServer:
      enabled: true
      clients:
        resources:
          limits:
            memory: 64Mi
          requests:
            memory: 16Mi
            cpu: 100m
      proxy:
        resources:
          limits:
            memory: 64Mi
          requests:
            memory: 16Mi
            cpu: 100m
    prometheus-node-exporter:
      resources:
        limits:
          memory: 64Mi
        requests:
          memory: 16Mi
          cpu: 100m
    defaultRules:
      rules:
        windows: false
    grafana:
      grafana.ini:
        auth.anonymous:
          enabled: false
      admin:
        existingSecret: prometheus
        userKey: grafana-admin-user
        passwordKey: grafana-admin-password
      ingress:
        enabled: true
        annotations:
          homer.service.name: Monitoring
          homer.item.name: Grafana
          homer.item.logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Grafana_logo.svg/1920px-Grafana_logo.svg.png"
          traefik.ingress.kubernetes.io/router.middlewares: kube-system-intranet-allowlist@kubernetescrd
        hosts:
          - grafana.{{ .Values.fqdn }}
        tls:
          - secretName: "{{ .Values.fqdn }}-tls"
            hosts:
              - grafana.{{ .Values.fqdn }}
      persistence:
        enabled: true
        storageClassName: local-path-persistent
        accessModes:
          - ReadWriteOnce
        size: 20Gi
        finalizers:
          - kubernetes.io/pvc-protection
      nodeSelector:
        # Schedule onto amd64 to specifically avoid raspberry pi to not wear the SD card
        kubernetes.io/arch: amd64
      resources:
        limits:
          memory: 2Gi
          cpu: null
        requests:
          memory: 1Gi
          cpu: 1000m
    prometheus:
      prometheusSpec:
        replicas: 1
        retention: 365d
        podAntiAffinity: hard
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 50Gi
        nodeSelector:
          # Schedule onto amd64 to specifically avoid raspberry pi to not wear the SD card
          kubernetes.io/arch: amd64
        resources:
          limits:
            memory: 3Gi
          requests:
            cpu: 500m
            memory: 1Gi
    extraManifests:
      - apiVersion: helm.cattle.io/v1
        kind: HelmChart
        metadata:
          name: loki
          namespace: kube-system
        spec:
          chart: loki
          repo: https://grafana.github.io/helm-charts
          version: 103.0.1
          targetNamespace: kube-system
          valuesContent: |-
            loki:
              commonConfig:
                replication_factor: 3
              schemaConfig:
                configs:
                  - from: "2024-04-01"
                    store: tsdb
                    object_store: s3
                    schema: v13
                    index:
                      prefix: loki_index_
                      period: 24h
              pattern_ingester:
                  enabled: true
              limits_config:
                allow_structured_metadata: true
                volume_enabled: true
              ruler:
                enable_api: true
            minio:
              enabled: false
            deploymentMode: SingleBinary
            singleBinary:
              replicas: 3
            # Zero out replica counts of other deployment modes
            backend:
              replicas: 0
            read:
              replicas: 0
            write:
              replicas: 0
            ingester:
              replicas: 0
            querier:
              replicas: 0
            queryFrontend:
              replicas: 0
            queryScheduler:
              replicas: 0
            distributor:
              replicas: 0
            compactor:
              replicas: 0
            indexGateway:
              replicas: 0
            bloomCompactor:
              replicas: 0
            bloomGateway:
              replicas: 0
{{- end }}
