{{- if (include "app.enabled" (list . "redis_insight")) }}
{{- include "app.require" (list . "Redis Insight" "redis" "Redis") -}}
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: redisinsight
  namespace: "{{ .Values.applicationsNamespace }}"
spec:
  chart: oci://oci.trueforge.org/truecharts/redisinsight
  version: 12.9.0
  targetNamespace: "{{ .Values.applicationsNamespace }}"
  values:
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                RI_ACCEPT_TERMS_AND_CONDITIONS: "true"
                RI_REDIS_HOST: redis-master
                RI_REDIS_PASSWORD:
                  secretKeyRef:
                    name: redis
                    key: redis-password
                    expandObjectName: false
    resources:
      requests:
        memory: {{ include "app.resources.memory" (list $ "256Mi") }}
        cpu: {{ include "app.resources.cpu" (list $ "250m") }}
      limits:
        memory: 1Gi
        cpu: null
    persistence:
      config:
        enabled: true
        type: emptyDir
      logs:
        enabled: true
        type: emptyDir
    global:
      traefik:
        fixedMiddlewares: []
    ingress:
      main:
        enabled: true
        annotations:
          homer.service.name: Administration
          homer.item.name: Redis Insight
          homer.item.logo: "https://raw.githubusercontent.com/RedisInsight/RedisInsight/6622d918f254dd8d46c98cf0ec2ea726e5727a9c/resources/logo.svg"
          traefik.ingress.kubernetes.io/router.middlewares: kube-system-intranet-allowlist@kubernetescrd,kube-system-cluster-admin-authentication@kubernetescrd
        hosts:
          - host: redis.{{ .Values.fqdn }}
            paths:
              - path: /
        tls:
          - secretName: "{{ .Values.fqdn }}-tls"
            hosts:
              - redis.{{ .Values.fqdn }}
{{- end }}
