{{- if .Values.primaryTenant }}
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: reflector
  namespace: kube-system
spec:
  chart: reflector
  repo: https://emberstack.github.io/helm-charts
  version: 10.0.30
  targetNamespace: kube-system
  # default-values: https://github.com/emberstack/kubernetes-reflector/blob/main/src/helm/reflector/values.yaml
  values:
    autoscaling:
      enabled: true
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 256Mi
{{- end }}
