{{- if .Values.primaryTenant }}
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: reflector
  namespace: kube-system
spec:
  chart: reflector
  repo: https://emberstack.github.io/helm-charts
  version: 10.0.55
  targetNamespace: kube-system
  serverSide: "true"
  forceConflicts: true
  values:
    autoscaling:
      enabled: true
    resources:
      requests:
        cpu: {{ include "app.resources.cpu" (list $ "100m") }}
        memory: {{ include "app.resources.memory" (list $ "256Mi") }}
      limits:
        memory: 512Mi
{{- end }}
