{{- if (include "app.enabled" (list . "stalwart")) }}
{{- include "app.require" (list . "Stalwart" "postgresql" "PostgreSQL") -}}
{{- include "app.require" (list . "Stalwart" "authentik" "Authentik") -}}
{{- include "app.require" (list . "Stalwart" "minio" "MinIO") -}}

# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: stalwart
#   namespace: "{{ .Values.applicationsNamespace }}"
# type: Opaque
# stringData:
#   bucket-access-key: "some_key"
#   bucket-secret-key: "some_key"
#   recovery-admin: "admin:some_password"
#   default-admin-password: "some_password"

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: stalwart
  namespace: "{{ .Values.applicationsNamespace }}"
spec:
  chart: stalwart
  repo: https://arch-anes.github.io/charts
  version: 0.1.7
  targetNamespace: "{{ .Values.applicationsNamespace }}"
  # default-values: https://github.com/arch-anes/charts/blob/main/charts/stalwart/values.yaml
  values:
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                STALWART_PUBLIC_URL: "https://mail.{{ .Values.fqdn }}"
                POSTGRESQL_PASSWORD:
                  secretKeyRef:
                    name: postgresql-pguser-stalwart
                    key: password
                    expandObjectName: false
                STALWART_RECOVERY_ADMIN:
                  secretKeyRef:
                    name: stalwart
                    key: recovery-admin
                    expandObjectName: false
                LDAP_BIND_PASSWORD:
                  secretKeyRef:
                    name: ldap
                    key: bind_password
                    expandObjectName: false
                BUCKET_ACCESS_KEY:
                  secretKeyRef:
                    name: stalwart
                    key: bucket-access-key
                    expandObjectName: false
                BUCKET_SECRET_KEY:
                  secretKeyRef:
                    name: stalwart
                    key: bucket-secret-key
                    expandObjectName: false
                SMTP_HOST:
                  secretKeyRef:
                    name: smtp
                    key: hostname
                    expandObjectName: false
                SMTP_NAME:
                  secretKeyRef:
                    name: smtp
                    key: username
                    expandObjectName: false
                SMTP_PASSWORD:
                  secretKeyRef:
                    name: smtp
                    key: password
                    expandObjectName: false
      apply-config:
        podSpec:
          containers:
            apply-config:
              env:
                STALWART_PASSWORD:
                  secretKeyRef:
                    name: stalwart
                    key: default-admin-password
                    expandObjectName: false
    configmap:
      authentik-blueprint:
        enabled: true
        data:
          blueprint.yaml: |
            # yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
            version: 1
            metadata:
              name: Stalwart provisionning
            entries:
              - id: postmaster-mail
                model: authentik_core.group
                identifiers:
                  name: postmaster
                attrs:
                  attributes:
                    mailAlias:
                      - "postmaster@{{ .Values.fqdn }}"

              - id: info-mail
                model: authentik_core.group
                identifiers:
                  name: info
                attrs:
                  attributes:
                    mailAlias:
                      - "info@{{ .Values.fqdn }}"
    ingress:
      main:
        enabled: true
        annotations:
          prometheus.io/probe: "false"
          homer.service.name: Administration
          homer.item.name: Stalwart
          homer.item.logo: https://raw.githubusercontent.com/stalwartlabs/stalwart/de7f0e8e37edce397a196bf47f08f1eaa2743078/img/logo-red.svg
        hosts:
          - host: mail.{{ .Values.fqdn }}
            paths:
              - path: /
                pathType: Prefix
          - host: {{ .Values.fqdn }}
            paths:
              - path: /.well-known/
                pathType: Prefix
        tls:
          - secretName: {{ .Values.fqdn }}-tls
            hosts:
              - mail.{{ .Values.fqdn }}
              - {{ .Values.fqdn }}
    stalwart:
      baseConfig: &postgresql
        "@type": PostgreSql
        host: postgresql-primary
        database: stalwart
        authUsername: stalwart
        authSecret:
          "@type": "EnvironmentVariable"
          variableName: POSTGRESQL_PASSWORD
      appliedConfig:
        - Tracer:
            matchOn: "@type"
            value:
              stdout:
                "@type": Stdout
                level: info
              otel:
                "@type": OtelHttp
                level: trace
                enable: {{ (include "app.enabled" (list . "tempo")) }}
                endpoint: http://tempo.kube-system.svc.cluster.local:4318/v1/traces
                httpAuth:
                  "@type": Unauthenticated
                enableLogExporter: false
                enableSpanExporter: true
        - Metrics:
            singleton: true
            value:
              openTelemetry:
                "@type": Disabled
              prometheus:
                {{- if include "metrics.enabled" . }}
                "@type": Enabled
                authSecret:
                  "@type": None
                {{- else }}
                "@type": Disabled
                {{- end }}
        - DataStore:
            singleton: true
            value: *postgresql
        - SearchStore:
            singleton: true
            value: *postgresql
        - BlobStore:
            singleton: true
            value: 
              "@type": S3
              bucket: "stalwart"
              region:
                "@type": Custom
                customEndpoint: http://minio
                customRegion: us-east-1
              accessKey: "%{env:BUCKET_ACCESS_KEY}%"
              secretKey:
                "@type": "EnvironmentVariable"
                variableName: BUCKET_SECRET_KEY
              securityToken:
                "@type": None
              sessionToken:
                "@type": None
        - Directory:
            matchOn: "@type"
            value:
              # TODO: verify
              ldap:
                # https://github.com/stalwartlabs/stalwart/discussions/521
                "@type": Ldap
                description: "Authentik LDAP"
                url: ldap://ak-outpost-ldap-outpost:389
                baseDn: {{ include "ldap.base_dn" . }}
                bindDn: "cn=ldapservice,{{ include "ldap.base_dn" . }}"
                bindSecret:
                  "@type": "EnvironmentVariable"
                  variableName: LDAP_BIND_PASSWORD
                # https://github.com/goauthentik/authentik/issues/17956
                filterLogin: "(|(mail=?)(mailAlias=?)(recoveryEmail=?))"
                filterMailbox: "(|(mail=?)(mailAlias=?)(recoveryEmail=?))"
                # https://github.com/stalwartlabs/stalwart/discussions/521#discussioncomment-12108062
                filterMemberOf: "(&(objectClass=posixGroup)(cn=?))"
                attrClass:
                  objectClass: true
                attrDescription:
                  sAMAccountName: true
                attrEmail:
                  mail: true
                attrEmailAlias:
                  mailAlias: true
                attrMemberOf:
                  memberOf: true
                attrSecretChanged:
                  pwdChangedTime: true
        - Authentication:
            singleton: true
            value:
              directoryId: "#ldap"
        - Domain:
            matchOn: name
            value:
              default:
                name: "mail.{{ .Values.fqdn }}"
        - SystemSettings:
            singleton: true
            value:
              defaultDomainId: "#default"
              defaultHostname: "mail.{{ .Values.fqdn }}"
        - Http:
            singleton: true
            value:
              useXForwarded: true
        - Certificate:
            matchOn: certificate
            value:
              default:
                certificate:
                  "@type": "File"
                  filePath: "/opt/stalwart/etc/certs/tls.crt"
                privateKey:
                  "@type": "File"
                  filePath: "/opt/stalwart/etc/certs/tls.key"
        - Email:
            singleton: true
            value:
              compressionAlgorithm: lz4
        - MtaStageAuth:
            singleton: true
            value:
              saslMechanisms:
                else: "[plain, login]"
              require:
                else: "listener != 'smtp'"
        - MtaRoute:
            matchOn: name
            value:
              relay:
                "@type": Relay
                name: relay
                address: "%{env:SMTP_HOST}%"
                port: 587
                implicitTls: false
                protocol: smtp
                authUsername: "%{env:SMTP_NAME}%"
                authSecret:
                  "@type": "EnvironmentVariable"
                  variableName: SMTP_PASSWORD
        - MtaDeliverySchedule:
            matchOn: name
            value:
              relay:
                name: relay
                queueId: "remote"
                expiry:
                  "@type": Ttl
                notify:
                  "@type": Default
                retry:
                  "@type": Custom
                  intervals:
                    - duration: "2m"
                    - duration: "5m"
                    - duration: "10m"
                    - duration: "15m"
                    - duration: "30m"
                    - duration: "1h"
                    - duration: "2h"
        - MtaOutboundStrategy:
            singleton: true
            value:
              route:
                else: "'relay'"
              schedule:
                else: "'relay'"
        - SpamClassifier:
            singleton: true
            value:
              model:
                "@type": FtrlFh
        - SpamRule:
            matchOn: name
            value:
              aws_ses_flagged:
                "@type": Header
                name: AWS_SES_FLAGGED
                description: "Trust AWS SES Spam and Virus verdicts"
                condition:
                  match:
                    - if: "(name_lower == 'x-ses-spam-verdict' || name_lower == 'x-ses-virus-verdict') && contains(value_lower, 'fail')"
                      then: "'AWS_SES_FLAGGED'"
                  else: "''"
        - SpamTag:
            matchOn: tag
            value:
              ses_flagged:
                "@type": Score
                tag: AWS_SES_FLAGGED
                score: 1000
    ingressRouteTCP:
      smtp:
        match: HostSNI(`mail.{{ .Values.fqdn }}`)
        entryPoint: mx
      smtps:
        match: HostSNI(`mail.{{ .Values.fqdn }}`)
        entryPoint: smtp
      imaps:
        match: HostSNI(`mail.{{ .Values.fqdn }}`)
        entryPoint: imap
      imap:
        enabled: false
      pop3:
        enabled: false
      pop3s:
        enabled: false
      submission:
        enabled: false
      sieve:
        enabled: false
    resources:
      limits:
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 256Mi
    metrics:
      main:
        enabled: {{ include "metrics.enabled" . }}
    persistence:
      data:
        storageClass: local-path-persistent-namespaced
      certificates:
        enabled: true
        type: secret
        objectName: "{{ .Values.fqdn }}-tls"
        expandObjectName: false
        mountPath: /opt/stalwart/etc/certs
        readOnly: true
{{- end }}

