{{- if (include "app.enabled" (list . "tdarr")) }}
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: tdarr
  namespace: "{{ .Values.applicationsNamespace }}"
spec:
  chart: oci://oci.trueforge.org/truecharts/tdarr
  version: 13.24.1
  targetNamespace: "{{ .Values.applicationsNamespace }}"
  # default-values: https://github.com/trueforge-org/truecharts/blob/master/charts/stable/tdarr/values.yaml
  values:
    workload:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        podSpec:
          annotations:
            backup.velero.io/backup-volumes: configs
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/instance
                        operator: In
                        values:
                          - jellyfin
                  topologyKey: "kubernetes.io/hostname"
          containers:
            main:
              env:
                serverIP: "0.0.0.0"
                serverPort: "8266"
                webUIPort: "8265"
                internalNode: "false"
                inContainer: "true"
                auth: "true"
    resources:
      requests:
        memory: 512Mi
        cpu: 250m
      limits:
        memory: 1Gi
        cpu: null
    global:
      traefik:
        fixedMiddlewares: []
    ingress:
      main:
        enabled: true
        annotations:    
          homer.service.name: Arr
          homer.item.logo: "https://home.tdarr.io/static/media/logo3-min.246d6df44c7f16ddebaf.png"
        hosts:
          - host: tdarr.{{ .Values.fqdn }}
            paths:
              - path: /
        tls:
          - secretName: "{{ .Values.fqdn }}-tls"
            hosts:
              - tdarr.{{ .Values.fqdn }}
    persistence:
      configs:
        type: pvc
        storageClass: local-path-persistent-namespaced
      server:
        type: pvc
        storageClass: local-path-persistent-namespaced
      logs:
        type: pvc
        storageClass: local-path-persistent-namespaced
      transcode-cache:
        type: pvc
        existingClaim: multimedia
        subPath: transcoding-cache
        mountPath: /temp
      media:
        type: pvc
        existingClaim: multimedia

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: tdarr-node
  namespace: "{{ .Values.applicationsNamespace }}"
spec:
  chart: oci://oci.trueforge.org/truecharts/tdarr-node
  version: 13.24.1
  targetNamespace: "{{ .Values.applicationsNamespace }}"
  # default-values: https://github.com/trueforge-org/truecharts/blob/master/charts/stable/tdarr-node/values.yaml
  values:
    workload:
      main:
        podSpec:
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/instance
                        operator: In
                        values:
                          - jellyfin
                  topologyKey: "kubernetes.io/hostname"
          containers:
            main:
              env:
                serverIP: "tdarr-comm"
                serverPort: "8266"
                inContainer: "true"
                nodeID: "PrincipalNode"
                apiKey:
                  secretKeyRef:
                    name: arr
                    key: tdarr_api_key
                    expandObjectName: false
              resources:
                requests:
                  memory: 512Mi
                  cpu: 250m
                limits:
                  memory: 2Gi
                  cpu: null
                  {{- include "gpu.device" (list . "Tdarr" .Values.applications.tdarr.gpu_vendor) | nindent 18 }}
    persistence:
      configs:
        type: pvc
        existingClaim: tdarr-configs
      logs:
        type: pvc
        existingClaim: tdarr-logs
      transcode-cache:
        type: pvc
        existingClaim: multimedia
        subPath: transcoding-cache
        mountPath: /temp
      media:
        type: pvc
        existingClaim: multimedia
{{- end }}
