{{- if (include "app.enabled" (list . "unpackerr")) }}
{{- include "app.require" (list . "Unpackerr" "transmission" "Transmission") -}}
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: unpackerr
  namespace: "{{ .Values.applicationsNamespace }}"
spec:
  chart: oci://oci.trueforge.org/truecharts/unpackerr
  version: 17.4.0
  targetNamespace: "{{ .Values.applicationsNamespace }}"
  # default-values: https://github.com/trueforge-org/truecharts/blob/master/charts/stable/unpackerr/values.yaml
  values:
    workload:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        podSpec:
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/instance
                        operator: In
                        values:
                          - transmission
                  topologyKey: "kubernetes.io/hostname"
          containers:
            main:
              env:
                UN_TRANSMISSION_0_URL: http://transmission:9091
                UN_TRANSMISSION_0_USER:
                  secretKeyRef:
                    name: transmission
                    key: username
                    expandObjectName: false
                UN_TRANSMISSION_0_PASS:
                  secretKeyRef:
                    name: transmission
                    key: password
                    expandObjectName: false
                {{- if (include "app.enabled" (list . "sonarr")) }}
                UN_SONARR_0_URL: http://sonarr:8989
                UN_SONARR_0_API_KEY:
                  secretKeyRef:
                    name: arr
                    key: sonarr_api_key
                    expandObjectName: false
                {{- end }}
                {{- if (include "app.enabled" (list . "radarr")) }}
                UN_RADARR_0_URL: http://radarr:7878
                UN_RADARR_0_API_KEY:
                  secretKeyRef:
                    name: arr
                    key: radarr_api_key
                    expandObjectName: false
                {{- end }}
                {{- if (include "metrics.enabled" .) }}
                UN_WEBSERVER_METRICS: "true"
                {{- end }}
    service:
      main:
        enabled: {{ include "metrics.enabled" . }}
        ports:
          main:
            enabled: true
            port: 5656
    metrics:
      main:
        enabled: {{ include "metrics.enabled" . }}
        endpoints:
          - port: main
            path: /metrics
            relabelings:
              - action: replace
                # Stable “instance” = app.kubernetes.io/instance
                sourceLabels: [__meta_kubernetes_namespace, __meta_kubernetes_pod_label_app_kubernetes_io_instance]
                separator: ":"
                replacement: "$1$2"
                targetLabel: instance
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 1Gi
        cpu: null
    persistence:
      config:
        enabled: false
      downloads:
        type: pvc
        subPath: Downloads
        existingClaim: multimedia
{{- end }}
