{{- if (include "app.enabled" (list . "vaultwarden")) }}
{{- include "app.require" (list . "Vaultwarden" "postgresql" "PostgreSQL") -}}
{{- include "app.require" (list . "Vaultwarden" "authentik" "Authentik") -}}
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: vaultwarden
  namespace: "{{ .Values.applicationsNamespace }}"
spec:
  chart: oci://oci.trueforge.org/truecharts/vaultwarden
  version: 30.5.0
  targetNamespace: "{{ .Values.applicationsNamespace }}"
  # default-values: https://github.com/trueforge-org/truecharts/blob/master/charts/stable/vaultwarden/values.yaml
  values:
    service:
      main:
        ports:
          main:
            targetPort: 80
    workload:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        podSpec:
          annotations:
            backup.velero.io/backup-volumes: data
          containers:
            main:
              envFrom: []
              env:
                DOMAIN: "https://vault.{{ .Values.fqdn }}"
                ADMIN_TOKEN:
                  secretKeyRef:
                    name: vaultwarden
                    key: admin_token
                    expandObjectName: false
                DATABASE_PASSWORD:
                  secretKeyRef:
                    name: postgresql-pguser-vaultwarden
                    key: password
                    expandObjectName: false
                DATABASE_URL: "postgresql://vaultwarden:$(DATABASE_PASSWORD)@postgresql-primary:5432/vaultwarden?sslmode=verify-full&sslrootcert=/etc/postgres/tls/ca.crt&sslcert=/etc/postgres/tls/tls.crt&sslkey=/etc/postgres/tls/tls.key"
                SIGNUPS_DOMAINS_WHITELIST: "{{ .Values.fqdn }}"
                INVITATIONS_ALLOWED: "false"
                SHOW_PASSWORD_HINT: "false"
                SSO_ENABLED: "true"
                SSO_ONLY: "true"
                SSO_SIGNUPS_MATCH_EMAIL: "true"
                SSO_SCOPES: "openid email profile offline_access"
                SSO_AUTHORITY: "https://auth.{{ .Values.fqdn }}/application/o/vaultwarden/"
                SSO_ALLOW_UNKNOWN_EMAIL_VERIFICATION: "false"
                SSO_CLIENT_CACHE_EXPIRATION: "0"
                SSO_CLIENT_ID:
                  secretKeyRef:
                    name: vaultwarden
                    key: client_id
                    expandObjectName: false
                SSO_CLIENT_SECRET:
                  secretKeyRef:
                    name: vaultwarden
                    key: client_secret
                    expandObjectName: false
                SMTP_HOST:
                  secretKeyRef:
                    name: smtp
                    key: hostname
                    expandObjectName: false
                SMTP_FROM: "vaultwarden@{{ .Values.fqdn }}"
                SMTP_PORT: "587"
                SMTP_SECURITY: "starttls"
                SMTP_USERNAME:
                  secretKeyRef:
                    name: smtp
                    key: username
                    expandObjectName: false
                SMTP_PASSWORD:
                  secretKeyRef:
                    name: smtp
                    key: password
                    expandObjectName: false
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 1Gi
        cpu: null
    global:
      traefik:
        fixedMiddlewares: []
    ingress:
      main:
        enabled: true
        annotations:
          homer.service.name: Administration
          homer.item.name: Vaultwarden
          homer.item.logo: "https://raw.githubusercontent.com/dani-garcia/vaultwarden/22f5e0496cca369af378c4f6379a0260b521fcbb/resources/vaultwarden-icon.svg"
        hosts:
          - host: vault.{{ .Values.fqdn }}
            paths:
              - path: /
        tls:
          - secretName: "{{ .Values.fqdn }}-tls"
            hosts:
              - vault.{{ .Values.fqdn }}
    persistence:
      data:
        enabled: true
        type: pvc
        storageClass: local-path-persistent-namespaced
      postgres-tls:
        enabled: true
        type: secret
        objectName: postgresql-cluster-cert
        expandObjectName: false
        mountPath: /etc/postgres/tls
        defaultMode: "0400"
    cnpg:
      main:
        enabled: false
    extraTpl:
      - apiVersion: external-secrets.io/v1
        kind: ExternalSecret
        metadata:
          name: vaultwarden
          namespace: "{{ .Values.applicationsNamespace }}"
        spec:
          refreshPolicy: CreatedOnce
          target:
            creationPolicy: Owner
            deletionPolicy: Retain
            name: vaultwarden
          dataFrom:
            - sourceRef:
                generatorRef:
                  apiVersion: generators.external-secrets.io/v1alpha1
                  kind: ClusterGenerator
                  name: huge-ascii-password-generator
              rewrite:
                - transform:
                    template: "admin_token"
            - sourceRef:
                generatorRef:
                  apiVersion: generators.external-secrets.io/v1alpha1
                  kind: ClusterGenerator
                  name: alphanumerical-password-generator
              rewrite:
                - transform:
                    template: client_id
            - sourceRef:
                generatorRef:
                  apiVersion: generators.external-secrets.io/v1alpha1
                  kind: ClusterGenerator
                  name: huge-alphanumerical-password-generator
              rewrite:
                - transform:
                    template: client_secret
      - apiVersion: v1
        kind: ConfigMap
        metadata:
          name: vaultwarden-authentik-blueprint
          namespace: "{{ .Values.applicationsNamespace }}"
        data:
          blueprint.yaml: |
            # yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
            version: 1
            metadata:
              name: Vaultwarden OAuth2 Provider
            entries:
              - id: vaultwarden-provider
                model: authentik_providers_oauth2.oauth2provider
                identifiers:
                  name: Provider for Vaultwarden
                attrs:
                  grant_types:
                    - authorization_code
                    - refresh_token
                  authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
                  invalidation_flow: !Find [authentik_flows.flow, [slug, default-invalidation-flow]]
                  client_type: confidential
                  sub_mode: user_username
                  redirect_uris:
                    - matching_mode: strict
                      url: "https://vault.{{ .Values.fqdn }}/identity/connect/oidc-signin"
                  signing_key: !Find [authentik_crypto.certificatekeypair, [name, authentik Self-signed Certificate]]
                  client_id: !File /blueprints/mounted/secret-vaultwarden/client_id
                  client_secret: !File /blueprints/mounted/secret-vaultwarden/client_secret
                  property_mappings:
                    - !Find [authentik_providers_oauth2.scopemapping, [scope_name, openid]]
                    - !Find [authentik_providers_oauth2.scopemapping, [name, Forced Email Verification Mapping]]
                    - !Find [authentik_providers_oauth2.scopemapping, [scope_name, profile]]
                    - !Find [authentik_providers_oauth2.scopemapping, [scope_name, offline_access]]
              - id: vaultwarden-app
                model: authentik_core.application
                identifiers:
                  slug: vaultwarden
                attrs:
                  name: Vaultwarden
                  provider: !KeyOf vaultwarden-provider
                  policy_engine_mode: any
                  meta_launch_url: "https://vault.{{ .Values.fqdn }}/#/sso?identifier=login"
      - apiVersion: networking.k8s.io/v1
        kind: Ingress
        metadata:
          name: vaultwarden-admin
          namespace: "{{ .Values.applicationsNamespace }}"
          annotations:
            homer.item.excluded: "true"
            traefik.ingress.kubernetes.io/router.middlewares: kube-system-intranet-allowlist@kubernetescrd
        spec:
          tls:
            - hosts:
                - vault.{{ .Values.fqdn }}
              secretName: "{{ .Values.fqdn }}-tls"
          rules:
            - host: vault.{{ .Values.fqdn }}
              http:
                paths:
                  - path: /admin
                    pathType: Prefix
                    backend:
                      service:
                        name: vaultwarden
                        port:
                          number: 80
{{- end }}
