{{- if (include "app.enabled" (list . "woodpecker")) }}
{{- include "app.require" (list . "Woodpecker" "postgresql" "PostgreSQL") -}}
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: woodpecker
#   namespace: "{{ .Values.applicationsNamespace }}"
# type: Opaque
# stringData:
#   WOODPECKER_GITEA: "true"
#   WOODPECKER_GITEA_URL: "https://gitea.example.org"
#   WOODPECKER_GITEA_CLIENT: "some-client-id"
#   WOODPECKER_GITEA_SECRET: "some-client-secret"

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: woodpecker
  namespace: "{{ .Values.applicationsNamespace }}"
spec:
  chart: oci://ghcr.io/woodpecker-ci/helm/woodpecker
  version: 3.6.4
  targetNamespace: "{{ .Values.applicationsNamespace }}"
  # default-values: https://github.com/woodpecker-ci/helm/blob/main/charts/woodpecker/values.yaml
  values:
    server:
      env:
        WOODPECKER_HOST: "https://ci.{{ .Values.fqdn }}"
        # WOODPECKER_OPEN: "true"
        WOODPECKER_DATABASE_DRIVER: postgres
        DB_PASSWORD:
          valueFrom:
            secretKeyRef:
              name: postgresql-pguser-woodpecker
              key: password
        WOODPECKER_DATABASE_DATASOURCE: "postgres://woodpecker:$(DB_PASSWORD)@postgresql-primary/woodpecker?sslmode=verify-full&sslrootcert=/etc/postgres/tls/ca.crt&sslcert=/etc/postgres/tls/tls.crt&sslkey=/etc/postgres/tls/tls.key"
      extraSecretNamesForEnvFrom:
        - woodpecker
      extraVolumeMounts:
        - name: postgresql-certs
          mountPath: /etc/postgres/tls
          readOnly: true
      extraVolumes:
        - name: postgresql-certs
          secret:
            secretName: postgresql-cluster-cert
            defaultMode: 0400
      ingress:
        enabled: true
        annotations:
          homer.service.name: Administration
          homer.item.name: Woodpecker
          homer.item.logo: "https://woodpecker-ci.org/img/logo.svg"
        hosts:
          - host: ci.{{ .Values.fqdn }}
            paths:
              - path: /
        tls:
          - secretName: "{{ .Values.fqdn }}-tls"
            hosts:
              - ci.{{ .Values.fqdn }}
    agent:
      replicaCount: 1
      env:
        WOODPECKER_SERVER: woodpecker-server:9000
        WOODPECKER_BACKEND: kubernetes
        WOODPECKER_BACKEND_K8S_NAMESPACE: "{{ .Values.applicationsNamespace }}"
        WOODPECKER_BACKEND_K8S_STORAGE_RWX: "false"
        WOODPECKER_BACKEND_K8S_POD_NODE_SELECTOR: "{\"runner\": \"true\"}"
      extraSecretNamesForEnvFrom:
        - woodpecker
{{- end }}
