{{- if (include "app.enabled" (list . "zfs_exporter")) }}
{{- include "app.require" (list . "ZFS Exporter" "prometheus" "Prometheus") -}}
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: zfs-exporter
  namespace: kube-system
spec:
  chart: zfs-exporter
  repo: https://arch-anes.github.io/charts
  version: 1.0.0
  targetNamespace: kube-system
  # default-values: https://github.com/arch-anes/charts/blob/main/charts/zfs-exporter/values.yaml
  values:
    workload:
      main:
        podSpec:
          containers:
            main:
              args:
                - --collector.dataset-snapshot
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
{{- end }}
